name: Test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Get
      run: go get -v -t -d ./...
    - name: Test
      run: go test ./...
